version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:debian
    privileged: true
    volumes:
      - ..:/workspaces/cmd-bell:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
