name: Build

on:
  push:
    branches:
      - "release"
  workflow_dispatch:

jobs:
  build:
    name: Build Release Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_suffix: ""
            asset_name: cmdbell-linux-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_suffix: ".exe"
            asset_name: cmdbell-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_suffix: ""
            asset_name: cmdbell-darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_suffix: ""
            asset_name: cmdbell-darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        working-directory: src
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -ldflags="-s -w" -o cmdbell${{ matrix.binary_suffix }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: src/cmdbell${{ matrix.binary_suffix }}
